// This file is auto-generated by the Amplify CLI when you run `amplify push`.
// Paste your Amplify configuration here, or let the CLI overwrite this file.
const awsconfig = {
  // replace with your actual AWS exports
};

export default awsconfig;
